/* 
 This file was generated by Dashcode.  
 You may edit this file to customize your widget or web page 
 according to the license.txt file included in the project.
 */

//
// Function: load()
// Called by HTML body element's onload event when the widget is ready to start
//


function load()
{

    dashcode.setupParts();

    
}


//
// Function: remove()
// Called when the widget has been removed from the Dashboard
//
function remove()
{
    // Stop any timers to prevent CPU usage
    // Remove any preferences as needed
    // widget.setPreferenceForKey(null, dashcode.createInstancePreferenceKey("your-key"));
}

//
// Function: hide()
// Called when the widget has been hidden
//
function hide()
{
    // Stop any timers to prevent CPU usage
}

//
// Function: show()
// Called when the widget has been shown
//
function show()
{
    // Restart any timers that were stopped on hide
}

//
// Function: sync()
// Called when the widget has been synchronized with .Mac
//
function sync()
{
    // Retrieve any preference values that you need to be synchronized here
    // Use this for an instance key's value:
    // instancePreferenceValue = widget.preferenceForKey(null, dashcode.createInstancePreferenceKey("your-key"));
    //
    // Or this for global key's value:
    // globalPreferenceValue = widget.preferenceForKey(null, "your-key");
}

//
// Function: showBack(event)
// Called when the info button is clicked to show the back of the widget
//
// event: onClick event from the info button
//
function showBack(event)
{
    var front = document.getElementById("front");
    var back = document.getElementById("back");

    if (window.widget) {
        widget.prepareForTransition("ToBack");
    }

    front.style.display = "none";
    back.style.display = "block";

    if (window.widget) {
        setTimeout('widget.performTransition();', 0);
    }
}

//
// Function: showFront(event)
// Called when the done button is clicked from the back of the widget
//
// event: onClick event from the done button
//
function showFront(event)
{
    var front = document.getElementById("front");
    var back = document.getElementById("back");

    if (window.widget) {
        widget.prepareForTransition("ToFront");
    }

    front.style.display="block";
    back.style.display="none";

    if (window.widget) {
        setTimeout('widget.performTransition();', 0);
    }
}

if (window.widget) {
    widget.onremove = remove;
    widget.onhide = hide;
    widget.onshow = show;
    widget.onsync = sync;
}

var e;
var target;
var count;


function check(){
    started = false;
}


var started =false;
var numbers;

var n=4;//размеры поля nXm
var m=5;
var k=2;//количество одинаковых карт
var timer;
var seconds = 0;
 
function startGame(event)
{   
    numbers = new Array(n);
    e=0;
    text.innerText= "Найдите все пары одинаковых букв";

    for(var i=0;i<n;i++)
        numbers[i] = new Array(m);
    for(var i=0;i<n;i++)
        for(var j=0;j<m;j++){
            document.getElementById("text"+i+j).style.background= "none";
            //document.getElementById("text"+i+j).innerText = "";
    }
    var b = Math.floor(Math.random()*15)+65;
    var nm = Math.floor(Math.random()*(32-n*m/k));
    for(var i=0;i<n*m/k;i++){
        for(var j=0;j<k;j++){
            do{ 
                var x = Math.floor(Math.random()*n);
                var y = Math.floor(Math.random()*m);
            }while( numbers[x][y]!=null);
            numbers[x][y]=nm;//String.fromCharCode(b+i);;
        }
        nm++;
    }
    started = true;
    target = 0;
    count = 0;
    
    clearInterval(timer);
    seconds = 0;
    time.innerText= "00:00";
    timer = setInterval(function () {
        seconds++;
        var t;
        var minutes = Math.floor(seconds/60);
        if(minutes<10)t="0"+minutes;
        else t = minutes;
        t+=":";
        var s = seconds - minutes*60;
        if(s<10)t+="0"+s;
            else t += s;
        time.innerText = t;
        if(minutes>59)clearInterval(timer);
    },1000);
}

    

function info(event)
{
    i.style.visibility ="visible";
    conf.style.visibility = "visible";
    iText.style.visibility ="visible";
    //iText.innerText="Вам будет показана таблица, в каждой ячейке которой скрыта буква. За один раз можно открыть пару ячеек. Если буквы в ячейках совпадут, ячейки останутся открытыми, если нет — закроются. \n\rВаша задача — как можно быстрее открыть всю таблицу.";
    //container.style.visibility ="visible";
    //instruction.style.visibility ="visible";
    
}


function ok(event)
{
    mistakes.style.visibility ="hidden";
    text2.style.visibility ="hidden";
    conf1.style.visibility ="hidden";
    //container.style.visibility ="hidden";
    i.style.visibility ="hidden";
    conf.style.visibility ="hidden";
    //instruction.style.visibility ="hidden";
    iText.style.visibility ="hidden";
}


function onClick(event)
{
        if(started){
        if(event.currentTarget.id.indexOf("text")==-1|| event.currentTarget.style.backgroundImage!="none")
        //event.currentTarget.innerText!="")
        return;
                
        var element = event.currentTarget;
        element.style.backgroundRepeat = "no-repeat";
        element.style.backgroundPosition = "center";
        var id = parseInt(event.currentTarget.id.substring(4));
        var x = Math.floor(id/10);
        var y = id%10;
        
        var url = "url(img/letters/"+numbers[x][y]+".svg)";
        element.style.backgroundImage = url;
        //element.innerText = numbers[x][y];
        if(target==0 || element == target ){
            target = element; return;
        }
        else{
            var tid = parseInt(target.id.substring(4));
            var tx = Math.floor(tid/10);
            var ty = tid%10;
            
            if(numbers[x][y]!=numbers[tx][ty]){
                started = false;
                setTimeout(function () {
                    element.style.background= "none"; 
                    target.style.background= "none";
                    //element.innerText = "";
                    //target.innerText = "";
                    target = 0;started = true;},1000);
            }
            else{
                count++;
                target = 0;started = true;
                
                if(count==n*m/2)
                {
                    started = false;
                    clearInterval(timer);
                    text2.innerText= "Ваше время: "+time.innerText;
                    mistakes.style.visibility = "visible";
                    text.innerText="";
                    text2.style.visibility = "visible";
                    conf1.style.visibility = "visible";
                    container.style.visibility ="visible";
                }
            }
        }
    }
}
